site_name: Python ROS Engine
site_description: A pure Python implementation of ROS2 functionality with bridging capabilities
site_author: Python ROS Engine Team

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - API Documentation: api.md
  - Bridging with Native ROS: bridging.md
  - Examples: examples.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true
  - meta

extra_css:
  - custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js