# Default configuration for Python ROS Engine

node:
  name: default_node
  namespace: /

publisher:
  topic: default_topic
  qos:
    reliability: reliable
    durability: volatile
    depth: 10

subscriber:
  topic: default_topic
  qos:
    reliability: reliable
    durability: volatile
    depth: 10

service:
  name: default_service
  qos:
    reliability: reliable
    durability: volatile
    depth: 10

parameters: {}

bridge:
  host: localhost
  port: 11311
  protocol: xmlrpc